set_property SRC_FILE_INFO {cfile:G:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/zybo_z7_led/new/zybo_z7.xdc rfile:../../../EE493_EC1_Zync_PWM_controller.srcs/zybo_z7_led/new/zybo_z7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { PWM0 }]; #IO_L23P_T3_35 Sch=led[0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M15   IOSTANDARD LVCMOS33 } [get_ports { PWM1 }]; #IO_L23N_T3_35 Sch=led[1]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { PWM2 }]; #IO_0_35 Sch=led[2]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { PWM3 }]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]
