# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0.xci
# IP: The module: 'sc7z010_demo_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0.xci
# IP: The module: 'sc7z010_demo_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sc7z010_demo_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
