# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0.xci
# IP: The module: 'clk_40MHz_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0.xci
# IP: The module: 'clk_40MHz_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.srcs/sources_1/bd/clk_40MHz/ip/clk_40MHz_clk_wiz_0_0/clk_40MHz_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_40MHz_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
