webtalk_init -webtalk_dir O:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.sim/sim_1/behav/xsim/xsim.dir/fancy_counter_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 28 23:22:43 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ab665133-5898-493b-a250-c4e40324e665" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "88c793a0ebdd4162861433474046c230" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "257488948 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "45.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16968_KB" -context "xsim\\usage"
webtalk_transmit -clientid 476689009 -regid "" -xml O:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.sim/sim_1/behav/xsim/xsim.dir/fancy_counter_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html O:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.sim/sim_1/behav/xsim/xsim.dir/fancy_counter_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm O:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.sim/sim_1/behav/xsim/xsim.dir/fancy_counter_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
