# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/image_rom/image_rom.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rom || ORIG_REF_NAME==image_rom} -quiet] -quiet

# IP: bd/image_rom/ip/image_rom_blk_mem_gen_0_0/image_rom_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==image_rom_blk_mem_gen_0_0 || ORIG_REF_NAME==image_rom_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/image_rom/image_rom_ooc.xdc
