# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio.xdc

# Block Designs: bd/zybo_z7_10_ps/zybo_z7_10_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps || ORIG_REF_NAME==zybo_z7_10_ps} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_processing_system7_0_0/zybo_z7_10_ps_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_processing_system7_0_0 || ORIG_REF_NAME==zybo_z7_10_ps_processing_system7_0_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_axi_gpio_0_0/zybo_z7_10_ps_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_axi_gpio_0_0 || ORIG_REF_NAME==zybo_z7_10_ps_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_axi_bram_ctrl_0_0/zybo_z7_10_ps_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zybo_z7_10_ps_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_blk_mem_gen_0_0/zybo_z7_10_ps_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_blk_mem_gen_0_0 || ORIG_REF_NAME==zybo_z7_10_ps_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_ps7_0_axi_periph_0/zybo_z7_10_ps_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_ps7_0_axi_periph_0 || ORIG_REF_NAME==zybo_z7_10_ps_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_rst_ps7_0_100M_0/zybo_z7_10_ps_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_rst_ps7_0_100M_0 || ORIG_REF_NAME==zybo_z7_10_ps_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_xbar_0/zybo_z7_10_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_xbar_0 || ORIG_REF_NAME==zybo_z7_10_ps_xbar_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_0/zybo_z7_10_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_auto_pc_0 || ORIG_REF_NAME==zybo_z7_10_ps_auto_pc_0} -quiet] -quiet

# IP: bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_1/zybo_z7_10_ps_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zybo_z7_10_ps_auto_pc_1 || ORIG_REF_NAME==zybo_z7_10_ps_auto_pc_1} -quiet] -quiet

# XDC: bd/zybo_z7_10_ps/zybo_z7_10_ps_ooc.xdc
