# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1.xci
# IP: The module: 'Zync_PWM_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1.xci
# IP: The module: 'Zync_PWM_rst_ps7_0_100M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/Documents/EE493_VHDL/EE493_EC1_Zync_PWM_controller/EE493_EC1_Zync_PWM_controller.srcs/sources_1/bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zync_PWM_rst_ps7_0_100M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
