# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio.xdc

# Block Designs: bd/sc7z010_demo/sc7z010_demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo || ORIG_REF_NAME==sc7z010_demo} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_processing_system7_0_0/sc7z010_demo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_processing_system7_0_0 || ORIG_REF_NAME==sc7z010_demo_processing_system7_0_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_axi_gpio_0_0/sc7z010_demo_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_axi_gpio_0_0 || ORIG_REF_NAME==sc7z010_demo_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_axi_bram_ctrl_0_0/sc7z010_demo_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_axi_bram_ctrl_0_0 || ORIG_REF_NAME==sc7z010_demo_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_blk_mem_gen_0_0/sc7z010_demo_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_blk_mem_gen_0_0 || ORIG_REF_NAME==sc7z010_demo_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_ps7_0_axi_periph_0/sc7z010_demo_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_ps7_0_axi_periph_0 || ORIG_REF_NAME==sc7z010_demo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_rst_ps7_0_50M_0/sc7z010_demo_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_rst_ps7_0_50M_0 || ORIG_REF_NAME==sc7z010_demo_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_xbar_0/sc7z010_demo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_xbar_0 || ORIG_REF_NAME==sc7z010_demo_xbar_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_auto_pc_0/sc7z010_demo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_auto_pc_0 || ORIG_REF_NAME==sc7z010_demo_auto_pc_0} -quiet] -quiet

# IP: bd/sc7z010_demo/ip/sc7z010_demo_auto_pc_1/sc7z010_demo_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sc7z010_demo_auto_pc_1 || ORIG_REF_NAME==sc7z010_demo_auto_pc_1} -quiet] -quiet

# XDC: bd/sc7z010_demo/sc7z010_demo_ooc.xdc
