webtalk_init -webtalk_dir G:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.sim/sim_1/behav/xsim/xsim.dir/image_dvi_top_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Apr  5 09:56:22 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fe8584c2-0d3e-41cd-b75f-261c8e297770" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2488ee94aca241d68067079494420888" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "568029 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "11" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "83.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "61492_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1843468475 -regid "" -xml G:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.sim/sim_1/behav/xsim/xsim.dir/image_dvi_top_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.sim/sim_1/behav/xsim/xsim.dir/image_dvi_top_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/Documents/EE493_VHDL/EE493_Lab4/EE493_Lab4.sim/sim_1/behav/xsim/xsim.dir/image_dvi_top_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
