# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z7.xdc

# Block Designs: bd/Zync_PWM/Zync_PWM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM || ORIG_REF_NAME==Zync_PWM} -quiet] -quiet

# IP: bd/Zync_PWM/ip/Zync_PWM_processing_system7_0_0/Zync_PWM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM_processing_system7_0_0 || ORIG_REF_NAME==Zync_PWM_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zync_PWM/ip/Zync_PWM_My_PWM_Core_0_0/Zync_PWM_My_PWM_Core_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM_My_PWM_Core_0_0 || ORIG_REF_NAME==Zync_PWM_My_PWM_Core_0_0} -quiet] -quiet

# IP: bd/Zync_PWM/ip/Zync_PWM_ps7_0_axi_periph_1/Zync_PWM_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM_ps7_0_axi_periph_1 || ORIG_REF_NAME==Zync_PWM_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/Zync_PWM/ip/Zync_PWM_rst_ps7_0_100M_1/Zync_PWM_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM_rst_ps7_0_100M_1 || ORIG_REF_NAME==Zync_PWM_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/Zync_PWM/ip/Zync_PWM_auto_pc_0/Zync_PWM_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zync_PWM_auto_pc_0 || ORIG_REF_NAME==Zync_PWM_auto_pc_0} -quiet] -quiet

# XDC: bd/Zync_PWM/Zync_PWM_ooc.xdc
