# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/seanc/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-20028-MSI/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.cache/wt [current_project]
set_property parent.project_path G:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo g:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib G:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.srcs/sources_1/new/clock_div.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.srcs/constrs_1/new/clock_div.xdc
set_property used_in_implementation false [get_files G:/Documents/EE493_VHDL/EE493_Lab1/EE493_Lab1.srcs/constrs_1/new/clock_div.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top clock_div -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef clock_div.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file clock_div_utilization_synth.rpt -pb clock_div_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
