# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/img_dvi_top.xdc

# Block Designs: bd/picture/picture.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picture || ORIG_REF_NAME==picture} -quiet] -quiet

# IP: bd/picture/ip/picture_blk_mem_gen_0_0/picture_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picture_blk_mem_gen_0_0 || ORIG_REF_NAME==picture_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/picture/picture_ooc.xdc
