# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_1/zybo_z7_10_ps_auto_pc_1.xci
# IP: The module: 'zybo_z7_10_ps_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_1/zybo_z7_10_ps_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_z7_10_ps_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_1/zybo_z7_10_ps_auto_pc_1.xci
# IP: The module: 'zybo_z7_10_ps_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/Documents/EE493_VHDL/EE493_Lenet-1_MNIST/EE493_Lenet-1_MNIST.srcs/sources_1/bd/zybo_z7_10_ps/ip/zybo_z7_10_ps_auto_pc_1/zybo_z7_10_ps_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_z7_10_ps_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
